services:
  backend:
    image: dispatching-backend:prod
    build:
      context: ./dispatching-backend
      dockerfile: Dockerfile
      args:
        PHP_ENV: production
    restart: unless-stopped
    volumes:
      - ./dispatching-backend:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/challenge:/home/challenge
      - ./nginx/ssl:/etc/ssl/private
      - ./nginx/conf.d/production.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./.output/public:/usr/share/nginx/html/output
      - ./dispatching-backend:/var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    networks:
      - app-network

  scheduler:
    image: dispatching-backend:prod
    restart: unless-stopped
    volumes:
      - ./dispatching-backend:/var/www/html
    env_file:
      - ./dispatching-backend/.env
    command: ["php", "artisan", "schedule:work"]
    depends_on:
      - db
      - redis
    networks:
      - app-network

  queue:
    image: dispatching-backend:prod
    restart: unless-stopped
    volumes:
      - ./dispatching-backend:/var/www/html
    env_file:
      - ./dispatching-backend/.env
    command: ["php", "artisan", "queue:work", "--sleep=3", "--tries=3", "--max-time=3600"]
    depends_on:
      - db
      - redis
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./storage/redis-data:/data
    networks:
      - app-network

  db:
    platform: linux/x86_64
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ./storage/db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
