server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name domain_name_here.com.au;

    ssl_certificate /etc/ssl/private/bundle.crt;
    ssl_certificate_key /etc/ssl/private/domain_name_here.com.au.key;

    # Security
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'TLS_AES_256_GCM_SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # HSTS
    add_header Strict-Transport-Security "max-age=15552000; includeSubDomains; preload" always;

    # Hide version
    server_tokens off;

    # Logging
    access_log /var/log/nginx/dispatching.access.log;
    error_log /var/log/nginx/dispatching.error.log warn;

    # File upload limit
    client_max_body_size 100M;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
    gzip_vary on;

    # Root & Index
    root /usr/share/nginx/html/output;
    index index.html;

    # Laravel API
    location /api/ {
        root /var/www/html/public;
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Laravel Storage
    location /storage/ {
        alias /var/www/html/storage/app/public/;
        access_log off;
        try_files $uri =404;
    }

    # Frontend
    location / {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        try_files $uri $uri/ /index.html;
    }

    # PHP Processing
    location ~ \.php$ {
        root /var/www/html/public;
        try_files $uri =404;

        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass backend:9000;
        fastcgi_index index.php;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name domain_name_here.com.au;

    return 301 https://domain_name_here.com.au$request_uri;
}
